Get lesson by current time.
nfqakademija/copy_paste pull request #5
Opened 2016-11-07 16:12 UTC by znav

If lesson does not exist or there are duplicate lessons throw an exception

2016-11-07 18:27 UTC, zilvinas-gasiunas commented on src/AppBundle/Controller/CurrentLessonController.php
> +     * @Route("/rezultatu_ivedimas/dabartine_pamoka", name="current_lesson_input_result")
route standartiskai su - ne su _

2016-11-07 18:28 UTC, lukosius requested changes

2016-11-07 18:28 UTC, lukosius commented on src/AppBundle/Service/LessonService.php
> +            var_dump("Jūsų pamokų laikai dubliuojasi, patikrinkite pamokų tvarkaraštį <br><br>" . $e);die;
Šitas nesąmonė. Turbūt geriau būtų sukurti LessonServiceException klasę ir mest Exception vietoj šito.

2016-11-07 18:28 UTC, lukosius commented on src/AppBundle/Service/LessonService.php
> +            var_dump("Šiuo metu nėra pamokos <br><br>" . $e); die;
Šitas nesąmonė. Turbūt geriau būtų sukurti LessonServiceException klasę ir mest Exception vietoj šito.

2016-11-07 18:28 UTC, zilvinas-gasiunas commented on app/config/services.yml
> +    app.lesson:
pavadinime taip pat reiktu, kad atsispindetu servisas

2016-11-10 11:48 UTC, lukosius approved these changes

2016-11-10 16:06 UTC, merged

2016-11-10 16:06 UTC, lukosius commented
Also, need to handle LessonException in Controller to display error to user. Probably you could try to implement flash messages https://symfony.com/doc/current/controller.html#flash-messages